export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" }
  public: {
    Tables: {
      kyc_documents: { Row: { created_at: string; doc_type: string; id: string; notes: string | null; status: string; storage_path: string; updated_at: string; user_id: string }; Insert: { created_at?: string; doc_type: string; id?: string; notes?: string | null; status?: string; storage_path: string; updated_at?: string; user_id: string }; Update: { created_at?: string; doc_type?: string; id?: string; notes?: string | null; status?: string; storage_path?: string; updated_at?: string; user_id?: string }; Relationships: [] }
      notifications: { Row: { body: string | null; created_at: string; id: string; read: boolean; title: string; user_id: string }; Insert: { body?: string | null; created_at?: string; id?: string; read?: boolean; title: string; user_id: string }; Update: { body?: string | null; created_at?: string; id?: string; read?: boolean; title?: string; user_id?: string }; Relationships: [] }
      profiles: { Row: { account_number: string; account_type: string; agencia: string; avatar_url: string | null; balance: number; balance_hidden: boolean; blocked: boolean; country: string; cpf: string | null; created_at: string; currency: string; date_of_birth: string | null; email: string | null; email_verified: boolean; face_verified: boolean; full_name: string; id: string; kyc_status: string; language: string; phone: string | null; pin_attempts: number; pin_hash: string | null; pin_locked_until: string | null; pin_salt: string | null; pix_key: string | null; swift: string; updated_at: string; verification_code: string | null; verification_expires_at: string | null }; Insert: { account_number: string; account_type?: string; agencia?: string; avatar_url?: string | null; balance?: number; balance_hidden?: boolean; blocked?: boolean; country?: string; cpf?: string | null; created_at?: string; currency?: string; date_of_birth?: string | null; email?: string | null; email_verified?: boolean; face_verified?: boolean; full_name?: string; id: string; kyc_status?: string; language?: string; phone?: string | null; pin_attempts?: number; pin_hash?: string | null; pin_locked_until?: string | null; pin_salt?: string | null; pix_key?: string | null; swift?: string; updated_at?: string; verification_code?: string | null; verification_expires_at?: string | null }; Update: { account_number?: string; account_type?: string; agencia?: string; avatar_url?: string | null; balance?: number; balance_hidden?: boolean; blocked?: boolean; country?: string; cpf?: string | null; created_at?: string; currency?: string; date_of_birth?: string | null; email?: string | null; email_verified?: boolean; face_verified?: boolean; full_name?: string; id?: string; kyc_status?: string; language?: string; phone?: string | null; pin_attempts?: number; pin_hash?: string | null; pin_locked_until?: string | null; pin_salt?: string | null; pix_key?: string | null; swift?: string; updated_at?: string; verification_code?: string | null; verification_expires_at?: string | null }; Relationships: [] }
      recipients: { Row: { account_number: string | null; agencia: string | null; bank: string; created_at: string; id: string; name: string; pix_key: string | null; user_id: string }; Insert: { account_number?: string | null; agencia?: string | null; bank: string; created_at?: string; id?: string; name: string; pix_key?: string | null; user_id: string }; Update: { account_number?: string | null; agencia?: string; bank?: string; created_at?: string; id?: string; name?: string; pix_key?: string | null; user_id?: string }; Relationships: [] }
      support_messages: { Row: { body: string; created_at: string; from_admin: boolean; id: string; image_url: string | null; priority: string; read_by_admin: boolean; read_by_user: boolean; status: string; subject: string | null; user_id: string }; Insert: { body: string; created_at?: string; from_admin?: boolean; id?: string; image_url?: string | null; priority?: string; read_by_admin?: boolean; read_by_user?: boolean; status?: string; subject?: string | null; user_id: string }; Update: { body?: string; created_at?: string; from_admin?: boolean; id?: string; image_url?: string | null; priority?: string; read_by_admin?: boolean; read_by_user?: boolean; status?: string; subject?: string | null; user_id?: string }; Relationships: [] }
      transactions: { Row: { amount: number; approved_at: string | null; approved_by: string | null; created_at: string; description: string | null; direction: string; id: string; pix_key: string | null; recipient_account: string | null; recipient_agencia: string | null; recipient_bank: string | null; recipient_name: string | null; reference: string; rejection_reason: string | null; sender_account: string | null; sender_bank: string | null; sender_name: string | null; status: string; type: string; user_id: string }; Insert: { amount: number; approved_at?: string | null; approved_by?: string | null; created_at?: string; description?: string | null; direction: string; id?: string; pix_key?: string | null; recipient_account?: string | null; recipient_agencia?: string | null; recipient_bank?: string | null; recipient_name?: string | null; reference?: string; rejection_reason?: string | null; sender_account?: string | null; sender_bank?: string | null; sender_name?: string | null; status?: string; type: string; user_id: string }; Update: { amount?: number; approved_at?: string | null; approved_by?: string | null; created_at?: string; description?: string | null; direction?: string; id?: string; pix_key?: string | null; recipient_account?: string | null; recipient_agencia?: string | null; recipient_bank?: string | null; recipient_name?: string | null; reference?: string; rejection_reason?: string | null; sender_account?: string | null; sender_bank?: string | null; sender_name?: string | null; status?: string; type?: string; user_id?: string }; Relationships: [] }
      user_roles: { Row: { created_at: string; id: string; role: Database["public"]["Enums"]["app_role"]; user_id: string }; Insert: { created_at?: string; id?: string; role?: Database["public"]["Enums"]["app_role"]; user_id: string }; Update: { created_at?: string; id?: string; role?: Database["public"]["Enums"]["app_role"]; user_id?: string }; Relationships: [] }
    }
    Views: { [_ in never]: never }
    Functions: {
      has_role: { Args: { _role: Database["public"]["Enums"]["app_role"]; _user_id: string }; Returns: boolean }
      admin_assert_role: { Args: Record<string, never>; Returns: undefined }
      admin_list_users: { Args: Record<string, never>; Returns: Database["public"]["Tables"]["profiles"]["Row"][] }
      admin_list_roles: { Args: Record<string, never>; Returns: Database["public"]["Tables"]["user_roles"]["Row"][] }
      admin_list_kyc: { Args: Record<string, never>; Returns: Database["public"]["Tables"]["kyc_documents"]["Row"][] }
      admin_list_transactions: { Args: Record<string, never>; Returns: Database["public"]["Tables"]["transactions"]["Row"][] }
      admin_list_notifications: { Args: Record<string, never>; Returns: Database["public"]["Tables"]["notifications"]["Row"][] }
      admin_list_support: { Args: Record<string, never>; Returns: Database["public"]["Tables"]["support_messages"]["Row"][] }
      admin_list_support_profiles: { Args: Record<string, never>; Returns: Database["public"]["Tables"]["profiles"]["Row"][] }
      admin_list_pending_transfers: { Args: Record<string, never>; Returns: Database["public"]["Tables"]["transactions"]["Row"][] }
    }
    Enums: { app_role: "admin" | "user" }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]
export type Tables<DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]) | { schema: keyof DatabaseWithoutInternals }, TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"]) : never = never> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends { Row: infer R } ? R : never : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]) ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends { Row: infer R } ? R : never : never
export type TablesInsert<DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals }, TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] : never = never> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends { Insert: infer I } ? I : never : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Insert: infer I } ? I : never
export type TablesUpdate<DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals }, TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] : never = never> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends { Update: infer U } ? U : never : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Update: infer U } ? U : never
export type Enums<DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals }, EnumName extends DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Enums"] : never = never> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Enums"][EnumName] : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Enums"] ? DefaultSchema["Enums"][DefaultSchemaTableNameOrOptions] : never
export type CompositeTypes<PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals }, CompositeTypeName extends PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"] : never = never> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals } ? DatabaseWithoutInternals[PublicSchema["CompositeTypes"]][CompositeTypeName] : never
export const Constants = { public: { Enums: { app_role: ["admin", "user"] } } } as const
